### ISSUE TITLE
input 시스템 작성

### ISSUE THREAD

**Issue by Perlmint** [Perlmint/yowane#4]
gui로 카와이하게

**Comment by TintypeMolly** [comment]
최초 (0, 0)은 기본 지정 되어있고, cursor로 지정되어있음.

현재 cursor로 사용되는 좌표는 red stroke, black fill

다음 갈 수 있는 주변 좌표들이 후보로 표시된다. 
(첫 좌표에서는 6방향, 두번째 좌표에서는 5방향... 같은 느낌이겠지)  
후보좌표는 red stroke, white fill

후보 좌표에 hover하면 red path가 나타나고, 마우스 치우면 사라짐.  
그 red path의 draw 순서는 격자보단 위고 나머지 모두보다는 아래다.

어떤 후보 좌표에 클릭하면, 기존에 cursor로 사용되는 좌표는 확정 좌표가 되고 black stroke, black fill이 된다.  
그리고 확정된 path는 black path가 된다.  
그리고 그 후보 좌표는 다시 cursor가 된다.

이렇게 gui에서 입력을 받으면서, direcion_array 같은 곳에 방향만을 저장한다.  
그래서 run을 하면 spacefill같은 객체?함수?에 넘겨줄 수 있도록.  
각 방향이 어떤 enum으로 되어있는지는 소스 참조. 나도 모름

end button을 만들어 놓고, 처음에는 비활성화 상태다가 (0, 0)에서 다른 점 한개를 클릭하면 활성화 되도록 한다.  
end button을 누르면 방향 입력 끝난거임.
