### ISSUE TITLE
[오늘처리] Oritatami Run

### ISSUE THREAD

**Issue by TintypeMolly** [Perlmint/yowane#5]
https://github.com/Perlmint/yowane/blob/master/index.html#L70

TODO 박아놨다.
누르면

1. JSON parse
2. sequence.split("")로 Array로 카와이이하게 잘라줌
3. drawOritatami 함수를 콜해서 저걸 인자로 던져준다

하도록 해주셈.

**Comment by Perlmint** [comment]
2는 걍 할 일이 없어서 펑
