### ISSUE TITLE
[오늘처리] 애니메이션 및 그림 디자인

### ISSUE THREAD

**Issue by TintypeMolly** [Perlmint/yowane#7]
이미 존재하는 구조체에 새 노드를 더해가는 식으로 오리타타미를 하잖아?

이 단위 동작에서 애니메이션을 다음과같이 그려줬으면 함.

1. 초기상태로 이미 존재하는 끄트머리 노드가 있다.
2. 새 노드 위치를 받아와서 path를 그린다. 이 때, 기존에 존재하는 노드로부터 새로 생길 노드 위치의 방향으로 그려지는 애니메이션을 적용한다. 그려지는 방식은 리니어든 큐빅 베지에든 상관 없음.
3. 이 애니메이션이 끝나면 새 노드(동그라미)를 그린다. 등장을 가능하면 cubic bezier로 했으면 좋겠다.
4. 끗

그리고 동그라미의 굵기를 2배 굵게 하고,

노드 안의 text에 따라서 색깔을 달리 해줬으면 함.

현재로써는 시드와 시퀀스에 등장하는 각각의 알파벳에 대하여 적당한 색을 하드코딩해도 될 것 같음.

**Comment by TintypeMolly** [comment]
@Perlmint Theme 넣으면 클로즈 부탁

**Comment by Perlmint** [comment]
implement theme d8e0e1364afc4751356102033589ea0c0fdf8dd7
